<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251119161843 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // Tabela pytań (musimy utworzyć najpierw)
        $this->addSql(<<<SQL
CREATE TABLE ff_question (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
)
SQL
        );

        // Tabela odpowiedzi z kluczem obcym do pytania
        $this->addSql(<<<SQL
CREATE TABLE ff_answer (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text VARCHAR(255) NOT NULL,
    points INT NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    question_id INT NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_ff_answer_question FOREIGN KEY (question_id)
        REFERENCES ff_question (id)
        NOT DEFERRABLE
)
SQL
        );

        $this->addSql(<<<SQL
CREATE INDEX idx_ff_answer_question_id
ON ff_answer (question_id)
SQL
        );

        // Tabela odpowiedzi użytkownika z kluczami obcymi do pytania i odpowiedzi
        $this->addSql(<<<SQL
CREATE TABLE ff_answer_player (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_text VARCHAR(255) NOT NULL,
    is_correct BOOLEAN NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    question_id INT NOT NULL,
    answer_id INT DEFAULT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_ff_answer_player_question FOREIGN KEY (question_id)
        REFERENCES ff_question (id)
        NOT DEFERRABLE,
    CONSTRAINT fk_ff_answer_player_answer FOREIGN KEY (answer_id)
        REFERENCES ff_answer (id)
        NOT DEFERRABLE
)
SQL
        );

        $this->addSql(<<<SQL
CREATE INDEX idx_ff_answer_player_question_id
ON ff_answer_player (question_id)
SQL
        );

        $this->addSql(<<<SQL
CREATE INDEX idx_ff_answer_player_answer_id
ON ff_answer_player (answer_id)
SQL
        );
    }

    public function down(Schema $schema): void
    {
        // Najpierw usuwamy tabele zależne
        $this->addSql('DROP TABLE ff_answer_player');
        $this->addSql('DROP TABLE ff_answer');
        $this->addSql('DROP TABLE ff_question');
    }
}
